apiVersion: apps/v1
kind: Deployment
metadata:
  name: formula-app-deployement
  annotations:
    kubernetes.io/change-cause: "Initial deployement of the app"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: formula-app
  template:
    metadata:
      name: myformulak8s
      labels:
        env: prod
        app: formula-app
        app.kubernetes.io/name: formula-app
    spec:
      containers:
      - name: formula-app
        image: malek1988/formulak8s
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 200Mi
            cpu: 200m
        ports:
        - containerPort: 80
          name: http-web-api
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80


---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: formula-app
  ports:
    - name: formula-app-port
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer


